
#
development:
  adapter: postgresql
  encoding: unicode
  database: bad_hair_development
  pool: 5
  host: localhost
  username: Froese
  password:

  # production:
  # adapter: postgresql
  # encoding: unicode
  # database: bad_hair_production
  # pool: 5
  # host: localhost
  # password:


  